site_name: PyCTF
theme:
  name: readthedocs
  highlightjs: true
#plugins:
#  - search
#  - mkdocstrings:
#      handlers:
#        # See: https://mkdocstrings.github.io/python/usage/
#        python:
#          options:
#            docstring_style: sphinx
markdown_extensions:
    - pymdownx.arithmatex:
        generic: true
        block_tag: 'pre'
#  - markdown_include.include:
#      base_path: .
#  - admonition
